### ISSUE TITLE
add: [GET] /users

### ISSUE THREAD

**Issue by tozastation** [fun-dev/fun-cloud-api#5]
## Overview -概要-
In case of receiving access token from client, server gets user information from database by using token.
(JWTのアクセストークンをクライアントから受け取った場合に，
データベースからアクセストークンに紐づくユーザの情報を取ってきてレスポンスとして返す)

## Task List -タスクリスト-
- [ ] : User.Select()の実装
- [ ] : UserControllerImpl.Get(c *gin.Context)の実装
- [ ] : MySQLDriver.CreateConnection()
- [ ] : var MySQLDriver.DB * sql.DB

--- Only Bug Case ---

## Steps to Reproduce the Problem
  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:
